spring:
  application:
    name: analyzer
  config:
    fail-fast: true
    import: configserver:http://localhost:8888
    retry:
      useRandomPolicy: true
      max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/